# Generated by Django 5.2.16 on 2026-07-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VencimientoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligacion', models.CharField(max_length=80, verbose_name='obligación')),
                ('periodo', models.CharField(max_length=60, verbose_name='período')),
                ('ultimo_digito', models.CharField(blank=True, help_text='Vacío = aplica a todos los NIT', max_length=1, verbose_name='último dígito del NIT')),
                ('fecha', models.DateField(verbose_name='fecha de vencimiento')),
                ('nota', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'vencimiento tributario',
                'verbose_name_plural': 'vencimientos tributarios',
                'ordering': ['fecha', 'obligacion'],
            },
        ),
    ]
