# Generated by Django 5.2.16 on 2026-07-13 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_empresa_exonerada_parafiscales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre del activo')),
                ('categoria', models.CharField(choices=[('edificaciones', 'Construcciones y edificaciones'), ('maquinaria', 'Maquinaria y equipo'), ('equipo_oficina', 'Equipo de oficina, muebles y enseres'), ('equipo_computo', 'Equipo de cómputo y comunicación'), ('vehiculos', 'Flota y equipo de transporte')], max_length=20)),
                ('fecha_adquisicion', models.DateField(verbose_name='fecha de adquisición')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='costo de adquisición')),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_fijos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'activo fijo',
                'verbose_name_plural': 'activos fijos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DepreciacionMensual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('detalle', models.JSONField(default=list, verbose_name='depreciación por activo')),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('asiento', models.JSONField(default=list)),
                ('explicacion', models.TextField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='core.empresa')),
            ],
            options={
                'verbose_name': 'depreciación mensual',
                'verbose_name_plural': 'depreciaciones mensuales',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'anio', 'mes'), name='depreciacion_unica_por_mes')],
            },
        ),
    ]
