# Generated by Django 5.2.16 on 2026-07-12 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_empresa_exonerada_parafiscales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('cedula', models.CharField(max_length=20, verbose_name='cédula')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='salario mensual')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cedula'), name='empleado_unico_por_empresa')],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionNomina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('detalle', models.JSONField(default=list, verbose_name='liquidación por empleado')),
                ('total_devengado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_deducciones', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_aportes_empleador', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_provisiones', models.DecimalField(decimal_places=2, max_digits=16)),
                ('asiento', models.JSONField(default=list)),
                ('explicacion', models.TextField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_nomina', to='core.empresa')),
            ],
            options={
                'verbose_name': 'liquidación de nómina',
                'verbose_name_plural': 'liquidaciones de nómina',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'anio', 'mes'), name='liquidacion_unica_por_mes')],
            },
        ),
    ]
