# Generated by Django 5.2.16 on 2026-07-13 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_exonerada_parafiscales'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadNomina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('he_diurna', 'Hora extra diurna (25%)'), ('he_nocturna', 'Hora extra nocturna (75%)'), ('recargo_nocturno', 'Recargo nocturno (35%)'), ('dominical_festivo', 'Recargo dominical/festivo (75%)'), ('comision', 'Comisiones'), ('bono_salarial', 'Bonificación salarial'), ('bono_no_salarial', 'Bonificación no salarial'), ('dias_no_laborados', 'Días no laborados'), ('incapacidad', 'Incapacidad (días a cargo de EPS/ARL)'), ('prestamo', 'Préstamo / libranza'), ('embargo', 'Embargo / otro descuento')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='horas o días')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor en pesos')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='nomina.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_nomina', to='core.empresa')),
            ],
            options={
                'verbose_name': 'novedad de nómina',
                'verbose_name_plural': 'novedades de nómina',
                'ordering': ['empleado', 'tipo'],
            },
        ),
    ]
