# Generated by Django 5.2.16 on 2026-07-11 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cufe', models.CharField(max_length=100, verbose_name='CUFE')),
                ('numero', models.CharField(max_length=50, verbose_name='número')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('nit_emisor', models.CharField(max_length=20, verbose_name='NIT del emisor')),
                ('nombre_emisor', models.CharField(max_length=200, verbose_name='emisor')),
                ('tipo_persona_emisor', models.CharField(max_length=2)),
                ('responsabilidad_emisor', models.CharField(blank=True, max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='retención en la fuente')),
                ('cuenta_puc', models.CharField(max_length=6, verbose_name='cuenta PUC propuesta')),
                ('nombre_cuenta_puc', models.CharField(max_length=120)),
                ('concepto_retencion', models.CharField(blank=True, max_length=40)),
                ('nivel', models.CharField(choices=[('automatica', 'Automática'), ('sugerida', 'Sugerida'), ('manual', 'Manual')], default='sugerida', max_length=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('explicacion', models.TextField(verbose_name='porqué de la propuesta')),
                ('asiento', models.JSONField(default=list, verbose_name='renglones del asiento propuesto')),
                ('xml_crudo', models.TextField(verbose_name='XML original (soporte)')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra', to='core.empresa')),
            ],
            options={
                'verbose_name': 'factura de compra',
                'verbose_name_plural': 'facturas de compra',
                'ordering': ['-creada'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cufe'), name='cufe_unico_por_empresa')],
            },
        ),
    ]
