# Generated by Django 5.2.16 on 2026-07-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0001_initial'),
        ('core', '0002_empresa_beta_cero'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='enviada_alegra',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enviada a Alegra'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='id_alegra',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='id del asiento en Alegra'),
        ),
        migrations.CreateModel(
            name='MapeoCuentaAlegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_puc', models.CharField(max_length=6, verbose_name='cuenta PUC')),
                ('id_alegra', models.PositiveIntegerField(verbose_name='id de la cuenta en Alegra')),
                ('nombre_alegra', models.CharField(blank=True, max_length=120, verbose_name='nombre en Alegra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_alegra', to='core.empresa')),
            ],
            options={
                'verbose_name': 'mapeo de cuenta Alegra',
                'verbose_name_plural': 'mapeos de cuenta Alegra',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cuenta_puc'), name='mapeo_unico_por_empresa')],
            },
        ),
    ]
