# Generated by Django 5.2.16 on 2026-07-12 01:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0002_facturacompra_enviada_alegra_facturacompra_id_alegra_and_more'),
        ('core', '0002_empresa_beta_cero'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('nota_credito', 'Nota crédito')], default='venta', max_length=15)),
                ('cufe', models.CharField(max_length=100, verbose_name='CUFE')),
                ('numero', models.CharField(max_length=50, verbose_name='número')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('nit_cliente', models.CharField(max_length=20, verbose_name='NIT del cliente')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='cliente')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('retencion_practicada', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='retefuente que practicó el cliente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('explicacion', models.TextField(verbose_name='porqué del registro')),
                ('asiento', models.JSONField(default=list, verbose_name='renglones del asiento propuesto')),
                ('xml_crudo', models.TextField(verbose_name='XML original (soporte)')),
                ('id_alegra', models.CharField(blank=True, default='', max_length=30, verbose_name='id del asiento en Alegra')),
                ('enviada_alegra', models.DateTimeField(blank=True, null=True, verbose_name='enviada a Alegra')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_venta', to='core.empresa')),
                ('factura_original', models.ForeignKey(blank=True, help_text='Venta que reversa esta nota crédito', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='causacion.facturaventa')),
            ],
            options={
                'verbose_name': 'factura de venta',
                'verbose_name_plural': 'facturas de venta',
                'ordering': ['-creada'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cufe'), name='cufe_venta_unico_por_empresa')],
            },
        ),
    ]
