# Generated by Django 5.2.16 on 2026-07-12 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0003_facturaventa'),
        ('core', '0002_empresa_beta_cero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20, verbose_name='NIT o cédula')),
                ('razon_social', models.CharField(max_length=200, verbose_name='razón social / nombre')),
                ('tipo_persona', models.CharField(choices=[('1', 'Persona jurídica'), ('2', 'Persona natural')], default='1', max_length=2)),
                ('declarante', models.BooleanField(default=True, help_text='Si no declara, aplican tarifas de retención más altas', verbose_name='declarante de renta')),
                ('autorretenedor', models.BooleanField(default=False, help_text='Se retiene a sí mismo: no se le practica retefuente', verbose_name='autorretenedor')),
                ('regimen_simple', models.BooleanField(default=False, help_text='El RST no es sujeto de retención (art. 911 E.T.)', verbose_name='Régimen Simple de Tributación')),
                ('verificado', models.BooleanField(default=False, help_text='Marcar cuando la información se haya cotejado con el RUT del tercero', verbose_name='verificado contra el RUT')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros', to='core.empresa')),
            ],
            options={
                'verbose_name': 'tercero',
                'verbose_name_plural': 'terceros',
                'ordering': ['razon_social'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nit'), name='tercero_unico_por_empresa')],
            },
        ),
    ]
