# Generated by Django 5.2.16 on 2026-07-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0004_tercero'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='facturas_fisicas', verbose_name='foto de la factura física'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='origen',
            field=models.CharField(choices=[('xml', 'XML DIAN'), ('foto', 'Foto de factura física')], default='xml', max_length=5),
        ),
    ]
