# Generated by Django 5.2.16 on 2026-07-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0005_facturacompra_imagen_facturacompra_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Del XML (PaymentDueDate); si falta, cartera asume 30 días', null=True, verbose_name='fecha de vencimiento'),
        ),
    ]
