# Generated by Django 5.2.16 on 2026-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0006_facturaventa_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='correo_cliente',
            field=models.EmailField(blank=True, default='', help_text='Del XML (Contact); destino de los recordatorios de cobro', max_length=254, verbose_name='correo del cliente'),
        ),
    ]
