# Generated by Django 5.2.16 on 2026-07-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0007_facturaventa_correo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='factura_original',
            field=models.ForeignKey(blank=True, help_text='Compra que reversa esta nota crédito de proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='causacion.facturacompra'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('nota_credito', 'Nota crédito de proveedor')], default='compra', max_length=15),
        ),
    ]
