# Generated by Django 5.2.16 on 2026-07-12 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0009_mapeo_alegra_semilla'),
        ('core', '0005_empresa_enviar_recordatorios_cobro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(choices=[('alegra', 'Alegra')], default='alegra', max_length=20)),
                ('usuario', models.CharField(max_length=200, verbose_name='correo o usuario de la API')),
                ('token', models.CharField(max_length=200, verbose_name='token de la API')),
                ('activa', models.BooleanField(default=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_contables', to='core.empresa')),
            ],
            options={
                'verbose_name': 'conexión contable',
                'verbose_name_plural': 'conexiones contables',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'proveedor'), name='conexion_unica_por_proveedor')],
            },
        ),
    ]
