# Generated by Django 5.2.16 on 2026-07-12 19:09

import core.cifrado
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0010_conexioncontable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexioncontable',
            name='token',
            field=core.cifrado.CampoCifrado(verbose_name='token de la API'),
        ),
    ]
