# Generated by Django 5.2.16 on 2026-07-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0012_cifrar_tokens_existentes'),
        ('core', '0007_empresa_ciudad_empresa_digito_verificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=40, verbose_name='rol de la app')),
                ('codigo', models.CharField(max_length=20, verbose_name='código de cuenta')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre de cuenta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cuentas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'cuenta del plan',
                'verbose_name_plural': 'plan de cuentas',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'rol'), name='cuenta_rol_unico_por_empresa')],
            },
        ),
    ]
