# Generated by Django 5.2.16 on 2026-07-13 15:50

import core.cifrado
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0013_cuentacontable'),
        ('core', '0007_empresa_ciudad_empresa_digito_verificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzonCorreo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servidor', models.CharField(help_text='Ej.: imap.gmail.com, outlook.office365.com', max_length=120, verbose_name='servidor IMAP')),
                ('puerto', models.PositiveIntegerField(default=993)),
                ('usuario', models.EmailField(max_length=254, verbose_name='correo')),
                ('clave', core.cifrado.CampoCifrado(verbose_name='contraseña (o contraseña de aplicación)')),
                ('carpeta', models.CharField(default='INBOX', max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_revision', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buzon', to='core.empresa')),
            ],
            options={
                'verbose_name': 'buzón de correo',
                'verbose_name_plural': 'buzones de correo',
            },
        ),
    ]
