# Generated by Django 5.2.16 on 2026-07-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0014_buzoncorreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='estado_dian',
            field=models.CharField(choices=[('pendiente', 'Pendiente de la DIAN'), ('aceptada', 'Aceptada por la DIAN'), ('rechazada', 'Rechazada por la DIAN')], default='pendiente', max_length=12, verbose_name='estado ante la DIAN'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='fecha_estado_dian',
            field=models.DateField(blank=True, null=True, verbose_name='fecha del estado DIAN'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='motivo_dian',
            field=models.TextField(blank=True, default='', verbose_name='motivo de la DIAN'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='rechazo_notificado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rechazo avisado por correo'),
        ),
    ]
