# Generated by Django 5.2.16 on 2026-07-19 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0015_facturaventa_estado_dian_and_more'),
        ('core', '0007_empresa_ciudad_empresa_digito_verificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='código de cuenta')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre de cuenta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_puc', to='core.empresa')),
            ],
            options={
                'verbose_name': 'cuenta del PUC',
                'verbose_name_plural': 'catálogo PUC',
                'ordering': ['codigo'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='puc_codigo_unico_por_empresa')],
            },
        ),
    ]
