# Generated by Django 5.2.16 on 2026-07-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion', '0016_cuentapuc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='concepto_retencion',
            field=models.CharField(blank=True, choices=[('honorarios', 'Honorarios y comisiones'), ('servicios', 'Servicios generales'), ('compras', 'Compras generales'), ('arrendamiento_inmueble', 'Arrendamiento de bienes inmuebles')], help_text='Concepto de retefuente con el que se causa a este proveedor (honorarios, servicios…). Vacío = la app lo decide por el texto.', max_length=30, verbose_name='concepto de retención fijo'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cuenta_gasto',
            field=models.CharField(blank=True, help_text='Código de la cuenta (auxiliar) a la que van SIEMPRE las compras de este proveedor. Vacío = la app la propone por el texto.', max_length=20, verbose_name='cuenta de gasto/costo fija'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='nombre_cuenta_gasto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
