# Generated by Django 5.2.16 on 2026-07-13 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_empresa_ciudad_empresa_digito_verificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaMenor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre del fondo')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='responsable')),
                ('monto_fijo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto del fondo')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_menores', to='core.empresa')),
            ],
            options={
                'verbose_name': 'caja menor',
                'verbose_name_plural': 'cajas menores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReembolsoCajaMenor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('asiento', models.JSONField(default=list)),
                ('explicacion', models.TextField()),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='cajamenor.cajamenor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos_caja_menor', to='core.empresa')),
            ],
            options={
                'verbose_name': 'reembolso de caja menor',
                'verbose_name_plural': 'reembolsos de caja menor',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='GastoCajaMenor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('cm_papeleria', 'Papelería y fotocopias'), ('cm_transporte', 'Transporte y combustible'), ('cm_cafeteria', 'Cafetería y aseo'), ('cm_otros', 'Otros gastos menores')], max_length=20, verbose_name='categoría')),
                ('concepto', models.CharField(max_length=200)),
                ('base', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor sin IVA')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='cajamenor.cajamenor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_caja_menor', to='core.empresa')),
                ('reembolso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='cajamenor.reembolsocajamenor')),
            ],
            options={
                'verbose_name': 'gasto de caja menor',
                'verbose_name_plural': 'gastos de caja menor',
                'ordering': ['fecha', 'creado'],
            },
        ),
    ]
