# Generated by Django 5.2.16 on 2026-07-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_beta_cero'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo_alertas',
            field=models.EmailField(blank=True, help_text='Vacío = sin alertas por correo', max_length=254, verbose_name='correo para alertas tributarias'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dias_anticipacion_alertas',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='días de anticipación de las alertas'),
        ),
    ]
