# Generated by Django 5.2.16 on 2026-07-12 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_correo_alertas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, verbose_name='correo del invitado')),
                ('rol', models.CharField(choices=[('admin', 'Administrador de empresa'), ('operador', 'Operador'), ('lectura', 'Solo lectura')], default='operador', max_length=10)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expira', models.DateTimeField(editable=False)),
                ('usada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.empresa')),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('admin', 'Administrador de empresa'), ('operador', 'Operador'), ('lectura', 'Solo lectura')], default='operador', max_length=10)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa'), name='membresia_unica')],
            },
        ),
    ]
