# Generated by Django 5.2.16 on 2026-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitacion_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='enviar_recordatorios_cobro',
            field=models.BooleanField(default=False, help_text='Correo con el estado de cuenta a clientes con facturas vencidas', verbose_name='enviar recordatorios de cobro'),
        ),
    ]
