# Generated by Django 5.2.16 on 2026-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_enviar_recordatorios_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='exonerada_parafiscales',
            field=models.BooleanField(default=True, help_text='PJ contribuyente de renta: no aporta salud 8.5%, SENA ni ICBF por empleados que ganen menos de 10 SMMLV', verbose_name='exonerada de parafiscales (art. 114-1)'),
        ),
    ]
