# Generated by Django 5.2.16 on 2026-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_exonerada_parafiscales'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, default='Bogotá D.C.', max_length=80, verbose_name='municipio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=1, verbose_name='dígito de verificación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='es_agente_retencion',
            field=models.BooleanField(default=True, help_text='Practica retefuente a sus proveedores', verbose_name='agente de retención en la fuente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='es_autorretenedor',
            field=models.BooleanField(default=False, verbose_name='autorretenedor de renta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_simple',
            field=models.BooleanField(default=False, help_text='La empresa tributa por el RST', verbose_name='Régimen Simple de Tributación (RST)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsable_iva',
            field=models.BooleanField(default=True, help_text="Antes 'régimen común'. Si no lo es, no discrimina IVA", verbose_name='responsable de IVA'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tarifa_ica_por_mil',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarifa del municipio para la actividad principal, en x1000', max_digits=5, verbose_name='tarifa de ICA (por mil)'),
        ),
    ]
