# Generated by Django 5.2.16 on 2026-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.SlugField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('referencia', models.CharField(help_text='Ej.: art. 392 E.T.', max_length=120, verbose_name='referencia normativa')),
                ('texto', models.TextField()),
                ('fuente_url', models.URLField(blank=True)),
                ('embedding', models.JSONField(blank=True, editable=False, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'artículo normativo',
                'verbose_name_plural': 'corpus normativo',
                'ordering': ['titulo'],
            },
        ),
    ]
