# Generated by Django 5.2.16 on 2026-07-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0002_corpus_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500, unique=True)),
                ('respuesta', models.TextField()),
                ('fuentes', models.JSONField(default=list)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'consulta en caché',
                'verbose_name_plural': 'consultas en caché',
                'ordering': ['-creada'],
            },
        ),
    ]
