# Generated by Django 5.2.16 on 2026-07-12 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('causacion', '0004_tercero'),
        ('core', '0002_empresa_beta_cero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractoBancario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre del extracto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'extracto bancario',
                'verbose_name_plural': 'extractos bancarios',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('sugerencia', models.CharField(choices=[('pago_cliente', 'Pago de cliente'), ('pago_cliente_parcial', 'Pago parcial de cliente'), ('pago_proveedor', 'Pago a proveedor'), ('gasto_bancario', 'Gasto bancario'), ('sin_identificar', 'Sin identificar')], default='sin_identificar', max_length=25)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('conciliado', 'Conciliado'), ('excepcion', 'Excepción')], default='pendiente', max_length=12)),
                ('asiento', models.JSONField(default=list, verbose_name='asiento propuesto')),
                ('explicacion', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to='core.empresa')),
                ('extracto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='conciliacion.extractobancario')),
                ('factura_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='causacion.facturacompra')),
                ('factura_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='causacion.facturaventa')),
            ],
            options={
                'verbose_name': 'movimiento bancario',
                'verbose_name_plural': 'movimientos bancarios',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
