# Generated by Django 5.2.16 on 2026-07-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientobancario',
            options={'ordering': ['extracto', 'fila'], 'verbose_name': 'movimiento bancario', 'verbose_name_plural': 'movimientos bancarios'},
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='fila',
            field=models.PositiveIntegerField(default=0, verbose_name='fila en el extracto'),
        ),
    ]
